### PR TITLE
pageserver - don't try to GC InMemoryLayers

### LINKED ISSUE #835: IntervalTree failed assertion
test_isolation crashed [here](https://app.circleci.com/pipelines/github/zenithdb/zenith/3075/workflows/bee75273-a3fa-476e-90ba-23ee657c5586/jobs/24733/artifacts)

My guess is that we're removing something not present? Also possible that there could be a bug in the IntervalTree impl, but less likely imo

```
thread 'WAL receiver thread' panicked at 'assertion failed: found_start_point', pageserver/src/layered_repository/interval_tree.rs:186:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: pageserver::layered_repository::interval_tree::IntervalTree<I>::remove
             at /home/circleci/project/pageserver/src/layered_repository/interval_tree.rs:186:9
   4: pageserver::layered_repository::layer_map::LayerMap::remove_historic
             at /home/circleci/project/pageserver/src/layered_repository/layer_map.rs:154:13
   5: pageserver::layered_repository::LayeredTimeline::evict_layer
             at /home/circleci/project/pageserver/src/layered_repository.rs:1280:13
   6: pageserver::layered_repository::evict_layer_if_needed
             at /home/circleci/project/pageserver/src/layered_repository.rs:1885:9
   7: pageserver::walreceiver::walreceiver_main
             at /home/circleci/project/pageserver/src/walreceiver.rs:300:17
   8: pageserver::walreceiver::thread_main
             at /home/circleci/project/pageserver/src/walreceiver.rs:155:19
   9: pageserver::walreceiver::launch_wal_receiver::{{closure}}
             at /home/circleci/project/pageserver/src/walreceiver.rs:107:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by patins**
Closes #835

### CODE REVIEW

File: pageserver/src/layered_repository/inmemory_layer.rs [hunk 1]
```diff
@@ -259,13 +259,17 @@ impl Layer for InMemoryLayer {
...
     fn delete(&self) -> Result<()> {
-        Ok(())
+        panic!("can't delete an InMemoryLayer")
     }
 
     fn is_incremental(&self) -> bool {
         self.incremental
     }
 
+    fn is_open(&self) -> bool {
```
Comment (hlinnaka) [inline pageserver/src/layered_repository/inmemory_layer.rs:269]: Let's be careful with the terms. Admittedly we haven't written these down anywhere, but this is how I think about these (I'll go and add these to the glossary):

Open: a layer where new WAL records can be appended to.
Closed: a layer that is read-only, no new WAL records can be appended to it.
Historical: synonym for closed
In-memory: A layer that is kept in memory, and will go away at a crash
On-disk: A layer that is stored on disk. If its end-LSN is older than disk_consistent_lsn, it is known to be fully flushed and fsync'd to local disk. (and S3?)
Frozen layer: an in-memory layer that is Closed.

With this terminology, the problem happens when GC removes a Closed In-memory layer, aka. a Frozen In-Memory layer. So long story short, let's call this function `is_on_disk` or `is_in_memory`. When an in-memory layer is frozen, it's no longer Open.

(With https://github.com/zenithdb/zenith/pull/864, the in-memory layers are also spilled to disk, so I think we'll need to come up with new terms. Ephemeral vs. Permanent, maybe?)

File: pageserver/src/layered_repository.rs [hunk 2]
```diff
@@ -1339,6 +1339,10 @@ impl LayeredTimeline {
         //
         let mut layers = self.layers.lock().unwrap();
         'outer: for l in layers.iter_historic_layers() {
+            if l.is_open() {
```
Comment (hlinnaka) [inline pageserver/src/layered_repository.rs:1342]: let's add a small comment here, explaining what would go wrong if you removed an open layer.

**Review by hlinnaka — APPROVED** [review]
