### PR TITLE
clippy cleanup #3

### LINKED ISSUE #67: File::write does not guarantee all bytes were written
Clippy says:
```
error: written amount is not handled. Use `Write::write_all` instead
   --> pageserver/src/walredo.rs:384:13
    |
384 |             config.write(b"shared_buffers=128kB\n")?;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::unused_io_amount)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount

error: written amount is not handled. Use `Write::write_all` instead
   --> pageserver/src/walredo.rs:385:13
    |
385 |             config.write(b"fsync=off\n")?;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
```

### PR DESCRIPTION
**Pull request by ericseppanen**
Fix some issues raised by clippy. Mostly trivial ones, though some allow 4-5 lines of code to be reduced to 1.

`File::write` does not guarantee all bytes are written; it behaves like the `write` syscall. Clippy points out `write_all` is probably a better choice.

Fixes #67.

### CODE REVIEW

File: pageserver/src/tui.rs [hunk 1]
```diff
@@ -171,13 +171,8 @@ pub fn ui_main() -> Result<(), Box<dyn Error>> {
...
 
         // If ther user presses 'q', quit.
-        if let Event::Input(key) = events.next()? {
-            match key {
-                Key::Char('q') => {
-                    break;
-                }
-                _ => (),
-            }
+        if let Event::Input(Key::Char('q')) = events.next()? {
```
Comment (hlinnaka) [inline pageserver/src/tui.rs:174]: The 'match' syntax makes sense again as soon as we add another key to the UI. Of course, we can easily change this back when that happens.

**Review by hlinnaka — APPROVED** [review]

File: pageserver/src/tui.rs (hunk 1 above)
Comment (ericseppanen) [reply pageserver/src/tui.rs:174]: I think you're right and it makes sense to leave this alone.
