### PR TITLE
 Fix confusion with layer start/end bounds and duplicates

### LINKED ISSUE #517: Garbage collection removes wrong layers
After running `pgbench -s100 -i`, I noticed that there are a lot of segments with histories like this:
```
-rw-r----- 1 heikki heikki 10489914 Sep  1 17:03 rel_1663_13990_16396_0_93_00000000621B408B
-rw-r----- 1 heikki heikki 10489914 Sep  1 17:03 rel_1663_13990_16396_0_93_00000000855FA085
-rw-r----- 1 heikki heikki 10489914 Sep  1 17:04 rel_1663_13990_16396_0_93_00000000B2819678
-rw-r----- 1 heikki heikki 17337382 Sep  1 17:05 rel_1663_13990_16396_0_93_00000000B2819678_000000011F586678
-rw-r----- 1 heikki heikki 10489914 Sep  1 17:05 rel_1663_13990_16396_0_93_000000011F586678
```
So it looks like we've removed the delta layers between those image layers, but left behind the image layers. There's no reason those image layers are needed, so something's wrong with the garbage collection

I did some debugging, and I think the reason is that `layers.remove_historic` call removes wrong layer. When we have determined that we need to remove e.g. the delta layer `rel_1663_13990_16396_0_93_00000000621B408B`, it looks up the layer in the BTreeMap using the start LSN, and actually finds and removes `rel_1663_13990_16396_0_93_00000000621B408B_00000000855FA085 `, prematurely. It won't try to remove the file `rel_1663_13990_16396_0_93_00000000621B408B` again on later GC iterations, because it's already been removed from the layer map, even though it still exists on disk.

Long story short, `LayerMap::remove_historic` needs to identify the entry to remove more accurately, using more than just the 'start_lsn'.

### PR DESCRIPTION
**Pull request by hlinnaka**
See commit messages for details

Fixes #517.

Note: this applies on top of PR #560

### CODE REVIEW

File: pageserver/src/layered_repository/image_layer.rs [hunk 1]
```diff
@@ -114,7 +114,7 @@ impl Layer for ImageLayer {
     }
 
     fn get_end_lsn(&self) -> Lsn {
-        self.lsn
+        self.lsn + 1
```
Comment (lubennikovaav) [inline pageserver/src/layered_repository/image_layer.rs:117]: Why this change?
In my understanding, `start_lsn == end_lsn` is important invariant of ImageLayer and some functions may rely on that.
I.e. ```start_lsn = prev_layer.get_end_lsn();```

Besides, I don't think it's a good idea to use some non-existing (and not aligned) lsn.

**Comment by hlinnaka** [comment]
I debugged the 'performance' test failure, analysis here: https://github.com/zenithdb/zenith/issues/567. In short, I believe it's a pre-existing bug that this PR happened to uncover.

File: pageserver/src/layered_repository/image_layer.rs (hunk 1 above)
Comment (hlinnaka) [reply pageserver/src/layered_repository/image_layer.rs:129]: So, previously we would create layers like this:
```
a: rel_1663_13990_16389_0_0_000000006CB4F3A0
b: rel_1663_13990_16389_0_0_0000000061E44298_000000006CB4F3A0
c: rel_1663_13990_16389_0_0_0000000061E44298
d: rel_1663_13990_16389_0_0_000000005CE5BAE0_0000000061E44298
```
The start-end LSN ranges of these layers, as reported by the `get_start_lsn()` and `get_end_lsn()` functions were:
```
a: 0/6CB4F3A0 - 0/6CB4F3A0
b: 0/61E44298 - 0/6CB4F3A0
c: 0/61E44298 - 0/61E44298
d: 0/5CE5BAE0 - 0/61E44298
```

There is some ambiguity here. If you're looking for page at LSN `0/6CB4F3A0`, which layer do you look into? There are two layers with that end-LSN: a and b. The correct answer is to look into layer 'b'. 'a' is a delta layer and it contains all the WAL leading up to that LSN, but it doesn't contain the record at that exact LSN, i.e. the end-boundary is exclusive. 'b' is an image layer and contains the state as it is at that LSN, so the end-boundary is inclusive.

This PR clarifies that, so that the end-LSN is always exclusive. So with this PR, the LSN ranges in the above situation would be:
```
a: 0/6CB4F3A0 - 0/6CB4F3A1
b: 0/61E44298 - 0/6CB4F3A0
c: 0/61E44298 - 0/61E44299
d: 0/5CE5BAE0 - 0/61E44298
```
Now it's more clear that you need to look at layer 'a'.

Comment (hlinnaka) [reply pageserver/src/layered_repository/image_layer.rs:130]: I updated the comments and README accordingly

File: pageserver/src/layered_repository/inmemory_layer.rs [hunk 2]
```diff
@@ -571,31 +578,60 @@ impl InMemoryLayer {
...
-                } else {
-                    before_segsizes.insert(*lsn, *size);
+                match lsn.cmp(&end_lsn) {
+                    Ordering::Less => {
+                        before_segsizes.insert(*lsn, *size);
+                    }
+                    Ordering::Equal => {
+                        // Page versions at the cutoff LSN will be stored in the
+                        // materialized image layer.
+                    }
```
Comment (patins) [inline pageserver/src/layered_repository/inmemory_layer.rs:594]: Don't these page versions need to exist in the temporary InMemoryLayers (at least before these temporary layers are replaced by historic on disk)

**Review by patins — COMMENTED** [review]
Sorry it's taken me a while to get to this. I will look through `interval_tree` more thoroughly tomorrow.

File: pageserver/src/layered_repository/inmemory_layer.rs (hunk 2 above)
Comment (hlinnaka) [reply pageserver/src/layered_repository/inmemory_layer.rs]: Ah, quite right! I mixed up `freeze` and `write_to_disk`

File: pageserver/src/layered_repository/layer_map.rs [hunk 3]
```diff
@@ -266,27 +277,19 @@ impl SegEntry {
...
-        }
+        self.historic.search(lsn)
     }
 
     pub fn newer_image_layer_exists(&self, lsn: Lsn) -> bool {
         // We only check on-disk layers, because
         // in-memory layers are not durable
 
-        for (_newer_lsn, layer) in self.historic.range(lsn..) {
+        for layer in self.historic.iter_newer(lsn) {
```
[the remark this answers is not in the document]
Comment (hlinnaka) [reply pageserver/src/layered_repository/layer_map.rs]: Cool, changed it to that.

File: pageserver/src/layered_repository/interval_tree.rs [hunk 4]
```diff
@@ -0,0 +1,439 @@
...
+    pub fn search(&self, key: I::Key) -> Option<Arc<I>> {
+        if let Some((_, p)) = self.points.range(..=key).next_back() {
+            // return the element with the highest end key that matches
+            let mut iter = p.elements.iter();
+            let mut highest_item = Arc::clone(iter.next().unwrap());
+            for i in iter {
+                if i.end_key() < highest_item.end_key() {
+                    continue;
+                }
+                highest_item = Arc::clone(i);
```
Comment (patins) [inline pageserver/src/layered_repository/interval_tree.rs:84]: It would be cool to avoid clone-ing the Arc until the return.
Also, I think you can do some iterator tricks here, maybe with `max_by_key`

File: pageserver/src/layered_repository/interval_tree.rs [hunk 5]
```diff
@@ -0,0 +1,439 @@
...
+
+            // Look at the previous point, and copy over elements that overlap with this
+            // new point
+            let mut new_elements: Vec<Arc<I>> = Vec::new();
+            if let Some((_, prev_point)) = self.points.range(..start_key).next_back() {
+                let overlapping_prev_elements = prev_point
+                    .elements
+                    .iter()
+                    .filter(|x| x.bounds().contains(&start_key))
+                    .map(|x| Arc::clone(x));
```
Comment (patins) [inline pageserver/src/layered_repository/interval_tree.rs:135]: I prefer `.map(Arc::clone)` or `.cloned()` (IIRC)

File: pageserver/src/layered_repository/interval_tree.rs [hunk 6]
```diff
@@ -0,0 +1,439 @@
...
+        // starting point.
+        loop {
+            if let Some((point_key, elem_iter)) = &mut self.elem_iter {
+                for elem in elem_iter {
+                    if elem.start_key() == *point_key {
+                        return Some(Arc::clone(elem));
+                    }
+                }
+            }
+            if let Some((point_key, point)) = self.point_iter.next() {
```
Comment (patins) [inline pageserver/src/layered_repository/interval_tree.rs:202]: Consider `?` here

File: pageserver/src/layered_repository/interval_tree.rs [hunk 7]
```diff
@@ -0,0 +1,439 @@
...
+/// interval to all the Points that are contained by the new interval (including the
+/// newly created Point).
+///
+/// To remove an interval, you scan the tree for all the Points that are contained by
+/// the removed interval, and remove it from the list in each Point.
+///
+/// Requirements and assumptions:
+///
+/// - Can store overlapping items
+/// - But there are not many overlapping items
```
Comment (patins) [inline pageserver/src/layered_repository/interval_tree.rs:35]: Maybe add a note that the interval must not change once added

File: pageserver/src/layered_repository/inmemory_layer.rs [hunk 8]
```diff
@@ -571,12 +578,19 @@ impl InMemoryLayer {
...
         let mut after_segsizes;
+        let mut after_oldest_lsn;
         if !dropped {
             before_segsizes = BTreeMap::new();
             after_segsizes = BTreeMap::new();
+            after_oldest_lsn = None;
             for (lsn, size) in inner.segsizes.iter() {
                 if *lsn > end_lsn {
                     after_segsizes.insert(*lsn, *size);
+                    after_oldest_lsn = Some(if let Some(previously_oldest) = after_oldest_lsn {
```
[the remark this answers is not in the document]
Comment (sharnoff) [reply pageserver/src/layered_repository/inmemory_layer.rs:589]: `.max` won't get the inner `min`. Here's a couple ideas:
```rs
after_oldest_lsn = match after_oldest_lsn {
    Some(old) => Some(old.min(*lsn)),
    None => Some(*lsn),
};

after_oldest_lsn = Some(after_oldest_lsn.min(Some(*lsn)).unwrap_or(*lsn));

after_oldest_lsn = Some(after_oldest_lsn.map(|old| old.min(*lsn)).unwrap_or(*lsn))
```

IMO the second one is the hardest to read, but it's worth mentioning. The first and third are essentially the same, just depends on how you want to phrase it. I'd personally go with one of those - kind of depends on the meaning you want to convey.

[the remark this answers is not in the document]
Comment (patins) [reply pageserver/src/layered_repository/inmemory_layer.rs:589]: My bad, misread. 

Also maybe
```
after_oldest_lsn = after_oldest_lsn.filter(|x| x < *lsn).unwrap_or(*lsn)
```

File: pageserver/src/layered_repository/interval_tree.rs [hunk 9]
```diff
@@ -0,0 +1,439 @@
...
+
+    /// Iterate over all items
+    pub fn iter(&self) -> IntervalIter<I> {
+        IntervalIter {
+            point_iter: self.points.range(..),
+            elem_iter: None,
+        }
+    }
+
+    pub fn insert(&mut self, item: Arc<I>) {
```
Comment (patins) [inline pageserver/src/layered_repository/interval_tree.rs:109]: It seems like remove will panic if you give an interval that is not in the struct (by ptr, duplicate ranges are allowed). Should we also panic in insert if we give an interval that is already in the struct (again, by ptr)?

File: pageserver/src/layered_repository/inmemory_layer.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (hlinnaka) [reply pageserver/src/layered_repository/inmemory_layer.rs]: Ugh, all of these look ugly to me.

I tried yet another approach: I created a new struct called `Accum`, to encapsulate this pattern. It's in a separate commit in this PR, what do you think of that approach? It's perhaps overkill just for this, but it does make these calls much nicer IMHO.

File: pageserver/src/layered_repository/interval_tree.rs (hunk 9 above)
Comment (hlinnaka) [reply pageserver/src/layered_repository/interval_tree.rs:119]: Added an assertion for that. It requires linear searching all the elements at the starting point, but we do that at `remove` anyway, and generally assume that there are very few overlapping intervals, so that's OK.

File: pageserver/src/layered_repository/interval_tree.rs (hunk 4 above)
Comment (patins) [reply pageserver/src/layered_repository/interval_tree.rs]: Bump

File: pageserver/src/layered_repository/interval_tree.rs (hunk 6 above)
Comment (patins) [reply pageserver/src/layered_repository/interval_tree.rs:223]: bump

**Review by patins — APPROVED** [review]
lgtm minus the bumped comments

File: pageserver/src/layered_repository/interval_tree.rs (hunk 6 above)
Comment (hlinnaka) [reply pageserver/src/layered_repository/interval_tree.rs:223]: That didn't seem like an improvement in readability to me, so I didn't do it. I added some comments on the control flow here, though.

File: pageserver/src/layered_repository/interval_tree.rs (hunk 4 above)
Comment (hlinnaka) [reply pageserver/src/layered_repository/interval_tree.rs]: I agree it would be cool. In practice, the case of overlapping layers is rare, so this won't matter much. If there is only one layer at this point, which is the typical case, then this will clone the Arc only once.

I wrote the above after trying various things with borrowing etc, but couldn't come up with a simple solution. Then I remembered the `Iterator::reduce` function, and that made this really simple. So rewrote this using `reduce`.

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Review by yeputons — COMMENTED** [review]
@hlinnaka `./run_clippy.sh` has some concerns. For some reason [Circle CI is silent](https://app.circleci.com/pipelines/github/zenithdb/zenith/2046/workflows/a78a4b7c-138a-4b73-81b2-c145db98c30f/jobs/14178)

```
    Checking pageserver v0.1.0 (/home/yeputons/job/zenith/pageserver)
error: called `is_none()` after searching an `Iterator` with `find`
   --> pageserver/src/layered_repository/interval_tree.rs:136:21
    |
136 | /                     point
137 | |                         .elements
138 | |                         .iter()
139 | |                         .find(|x| Arc::ptr_eq(x, &item))
140 | |                         .is_none(),
    | |__________________________________^
    |
    = note: `-D clippy::search-is-some` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some
help: use `!_.any()` instead
    |
136 |                     !point
137 |                         .elements
138 |                         .iter().any(|x| Arc::ptr_eq(x, &item)),
    |

error: this expression borrows a reference (`&std::sync::Arc<I>`) that is immediately dereferenced by the compiler
   --> pageserver/src/layered_repository/interval_tree.rs:183:63
    |
183 |             point.elements.retain(|other| !Arc::ptr_eq(other, &item));
    |                                                               ^^^^^ help: change this to: `item`
    |
    = note: `-D clippy::needless-borrow` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: could not compile `pageserver` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by yeputons** [comment]
Looks like I'm running a newer Rustc/Clippy than CircleCI, but warnings still make sense to me, although nitpicky.

I will downgrade to be in sync with CI versions.
