### PR TITLE
Do not garbage collect child referenced data in parent branch

### LINKED ISSUE #865: GC removes data in parent branch that might be referenced by child branches
This is a dedicated issue for one of the problems described in #863.

We do not track which layers are needed by child branch. So it is possible to garbage collect layers in parent branch and then fail to retrieve data in child branch. We already collect branchpoints and pass them to gc routine, but then we only keep layers that directly contain branchpoints. Layers that are preceding branchpoints can be referenced by child branch and currently we don't take this into account. First half of the fix is trivial and already implemented in #863. It changes gc logic to keep not only branchpoints but all preceding layers too. This introduces problem with bloat. If child branch no longer needs these layers from parent they won't be deleted, which leads to wasted disk space. I'll try to investigate a gc strategy that can allow child timelines detect when these layers are no longer needed and delete them from parent branch. This is complicated by taking into account long branch chains. So maybe it is preferable to land simple fix sooner and create separate issue for avoiding bloat.

### PR DESCRIPTION
**Pull request by LizardWizzard**
This is the second half of #863. This prevents gc to collect data that still might be referenced in child branches. This doesn't include fix for bloat that might happen when there is a long living child branch. In that case gc in parent branch cannot delete data for child branch even if it is no longer needed. (As discussed I'll create separate issue for that)

This is based on #877 so see second commit for actual changes.

Resolves #865

### CODE REVIEW

File: pageserver/src/layered_repository/delta_layer.rs [hunk 1]
```diff
@@ -526,7 +526,7 @@ impl DeltaLayer {
 
         *inner = DeltaLayerInner {
             loaded: true,
-            book: None,
+            book: Some(book),
```
Comment (LizardWizzard) [inline pageserver/src/layered_repository/delta_layer.rs:529]: This seems like an unrelated change, but it looks confusing and I think this is correct. More context:  I've faced a panic in an unwrap call [here](https://github.com/zenithdb/zenith/blob/main/pageserver/src/layered_repository/delta_layer.rs#L206) when I was writing the unittest, and it looks strange that we never set this book to something other than None. 

@hlinnaka Is it correct?

Also I'm thinking about adding a lazy behaviour in VirtualFile, so we can call open on it but it will be actually opened on first read/write operation. Thoughts?

**Comment by LizardWizzard** [comment]
@hlinnaka @lubennikovaav I've added one more check to test_branch_behind, so I think this is ready to be merged. Please take a look

**Review by lubennikovaav — COMMENTED** [review]
LGTM

It would be nice to add another unit test that illustrates the fact that data in the parent is kept forever if branchpoint exists:

1.branch_timeline()
2. create more layers on newtline to make it "independent" from parent
3. gc parent timeline
4. check that layer before branchpoint still exists

File: pageserver/src/repository.rs [hunk 2]
```diff
@@ -829,6 +829,23 @@ mod tests {
...
+        let repo =
+            RepoHarness::create("test_retain_data_in_parent_which_is_needed_for_child")?.load();
+        let tline = repo.create_empty_timeline(TIMELINE_ID)?;
+
+        make_some_layers(&tline)?;
+
+        repo.branch_timeline(TIMELINE_ID, NEW_TIMELINE_ID, Lsn(0x40))?;
+        let newtline = repo.get_timeline(NEW_TIMELINE_ID)?;
+
+        // this removes layers before lsn 40 (50 minus 10), so there are two remaining layers, image and delta for 31-50
```
[the remark this answers is not in the document]
Comment (LizardWizzard) [reply pageserver/src/repository.rs:846]: IMO it is still valid, since both tests perform gc in a same way. I can remove it so it is in place only in the first test

**Comment by LizardWizzard** [comment]
@lubennikovaav I've added the test case you've mentioned. Please take a look

**Review by lubennikovaav — APPROVED** [review]

File: pageserver/src/layered_repository/delta_layer.rs (hunk 1 above)
Comment (LizardWizzard) [reply pageserver/src/layered_repository/delta_layer.rs:533]: @hlinnaka I'm not sure about this change, please take a look when you have a chance

Comment (hlinnaka) [reply pageserver/src/layered_repository/delta_layer.rs:533]: Huh, yeah, that was clearly a bug in 9300107cdfb3ee168c0ee2a553f093d8a064b2a1. Good catch!

But now I'm a bit concerned; why was this not caught by any tests? Do we not have any test coverage for `get_page_reconstruct_data` on a delta layer?

Comment (hlinnaka) [reply pageserver/src/layered_repository/delta_layer.rs:533]: > Also I'm thinking about adding more lazy behaviour to VirtualFile, so we can call open on it but it will be actually opened on first read/write operation. Thoughts?

Two thoughts:
1. Currently, we only open a VirtualFile if we're going to read it. So it wouldn't make any difference in practice.
2. I think it's good to check that the file exists and is accessible, on the `open` call. The simple way to do that is to actually open the file.

Comment (LizardWizzard) [reply pageserver/src/layered_repository/delta_layer.rs:533]: > why was this not caught by any tests?

Yeah, thats why I wasnt sure about the change

> Do we not have any test coverage for get_page_reconstruct_data on a delta layer?

It seems that this is the case, I've put a panic inside get_page_reconstruct_data for delta layer and rust tests have passed (tried on main)

I've managed to get basic coverage using cargo-tarpaulin with
```
cargo install cargo-tarpaulin
cargo tarpaulin -v --avoid-cfg-tarpaulin
```
So it shows basic line coverage in the report:
```
42.35% coverage, 4418/10433 lines covered
```
It outputs line numbers for each file in the report so it is possible to see what is not covered

> Two thoughts:

Makes sense, lets keep it as it is now
