### PR TITLE
propagate pageserver http error messages to zenith cli

### LINKED ISSUE #525: Error propagation in pageserver http api/cli
Trying to create branch with the same name again:

```
`--> ./target/debug/zenith branch br main                                                            
Created branch 'br' at 0/16B9150 for tenant: fdc09209aa9bd8c6f39162a9a9067feb

`--> ./target/debug/zenith branch br main
branch command failed: HTTP status server error (500 Internal Server Error) for url (http://127.0.0.1:9898/v1/branch)
```

### PR DESCRIPTION
**Pull request by LizardWizzard**
closes #525

### CODE REVIEW

**Comment by funbringer** [comment]
I feel like this kind of change should include a "before/after" comparison in a commit message (and probably a copy-paste in PR's description). Overall, I'm for descriptive commit messages.

**Comment by funbringer** [comment]
Follow-up:

Current printing logic seems to hide the crucial string behind the visual clutter:

```diff
- branch command failed: HTTP status server error (500 Internal Server Error) for url (http://127.0.0.1:9898/v1/branch)
+ branch command failed: Http error (500 Internal Server Error) at http://127.0.0.1:9898/v1/branch. Error: branch br already exists
```

Speaking of the error code: I don't think 500 is a good fit here. The API is misused, so this should be a `4xx` error.

**Comment by LizardWizzard** [comment]
@funbringer See https://github.com/zenithdb/zenith/issues/525#issuecomment-912607763 IMO this PR makes an improvement, but this is not a final state. For sure API errors should correspond to proper status codes.

**Comment by funbringer** [comment]
> IMO this PR makes an improvement, but this is not a final state

True, wouldn't it be better to push it a little bit further? Say, we could print just the error string and only print the host:port + HTTP code if we failed to get a json.

**Comment by LizardWizzard** [comment]
> Say, we could print just the error string and only resort to host:port + HTTP code if we failed to get a jso

I'm ok to change the message format, here I've just mimicked how reqwest error looks like. I think URI can also be useful in case we failed to parse json, what do you think?

**Comment by funbringer** [comment]
> I think URI can also be useful in case we failed to parse json, what do you think?

Sure! What I really meant was "if we failed to extract the payload".

**Comment by LizardWizzard** [comment]
newly added test check_restored_datadir_content knocked down some of the tests, shouldn't relate to this PR. Failed on main too

fyi @lubennikovaav

**Comment by LizardWizzard** [comment]
rebased on main @funbringer please take a look and let's merge this :)

**Review by kelvich — APPROVED** [review]

File: control_plane/src/storage.rs [hunk 1]
```diff
@@ -22,6 +23,28 @@ use zenith_utils::connstring::connection_address;
 
 const HTTP_BASE_URL: &str = "http://127.0.0.1:9898/v1";
 
+pub trait ResponseErrorMessageExt {
+    fn error_from_error_body(self) -> Result<Self>
+    where
+        Self: Sized;
+}
```
Comment (funbringer) [inline control_plane/src/storage.rs:30]: Since this is an extension method, could you move `Sized` to `ResponoseErrorMessageExt: Sized`? This would be shorter. Also, could you give it a shorter name with less repetition? E.g. `validate_body`.

**Comment by funbringer** [comment]
To be clear: I'm not a big fan of so called extension methods. Usually, they needlessly complicate code for little gain, but I don't want to fight over this particular case. So I propose fixing my nits and merging this stuff. Maybe we'll come up with style guides later.

**Comment by LizardWizzard** [comment]
> I'm not a big fan of so called extension methods.

IMO in this case it is just shorter and looks nicer with chaining

**Review by funbringer — APPROVED** [review]

**Comment by LizardWizzard** [comment]
I had to slightly rework this because of changed return type to be `reqwest::Result` and not being able to construct a `reqwest::Error` because of a private constructor

File: control_plane/src/storage.rs [hunk 2]
```diff
@@ -22,6 +24,42 @@ use zenith_utils::connstring::connection_address;
...
+pub enum PageserverHttpError {
+    #[error("Reqwest error")]
+    Transport(#[from] reqwest::Error),
+
+    #[error("Error: {0}")]
+    Response(String),
+}
+
+pub trait ResponseErrorMessageExt: Sized {
+    fn error_from_body(self) -> Result<Self, PageserverHttpError>;
```
Comment (funbringer) [inline control_plane/src/storage.rs:37]: Could we create a type alias `Result = Result<Self, PageserverHttpError>`?

File: control_plane/src/storage.rs [hunk 3]
```diff
@@ -22,6 +24,42 @@ use zenith_utils::connstring::connection_address;
...
+        match self.json::<HttpErrorBody>() {
+            Ok(err_body) => Err(PageserverHttpError::Response(format!(
+                "Error: {}",
+                err_body.msg
+            ))),
+            Err(_) => Err(PageserverHttpError::Response(format!(
+                "Http error ({}) at {}.",
+                status.as_u16(),
+                url
+            ))),
```
Comment (funbringer) [inline control_plane/src/storage.rs:58]: I'd extract common subexpression:

```rust
Err(PageserverHttpError::Response(match self.json::<HttpErrorBody>() { ... })
```

File: control_plane/src/storage.rs [hunk 4]
```diff
@@ -22,6 +24,42 @@ use zenith_utils::connstring::connection_address;
...
+}
+
+impl ResponseErrorMessageExt for Response {
+    fn error_from_body(self) -> Result<Self, PageserverHttpError> {
+        if !(self.status().is_client_error() || self.status().is_server_error()) {
+            return Ok(self);
+        }
+
+        // reqwest do not export it's error construction utility functions, so lets craft the message ourselves
+        let status = self.status();
```
Comment (funbringer) [inline control_plane/src/storage.rs:47]: This could be moved to the beginning and reused in if-condition.

File: control_plane/src/storage.rs [hunk 5]
```diff
@@ -198,33 +236,36 @@ impl PageServerNode {
...
     }
 
-    pub fn tenant_list(&self) -> reqwest::Result<Vec<String>> {
+    pub fn tenant_list(&self) -> Result<Vec<String>, PageserverHttpError> {
         Ok(self
             .http_request(Method::GET, format!("{}/{}", self.http_base_url, "tenant"))
             .send()?
-            .error_for_status()?
+            .error_from_body()?
             .json()?)
```
Comment (funbringer) [inline control_plane/src/storage.rs:244]: I'll leave this here solely for comparison:

```rust
let req = self
    .http_request(Method::GET, format!("{}/{}", self.http_base_url, "tenant"))
    .send()?;

Ok(validate_body(req)?.json()?)
```

**Review by funbringer — APPROVED** [review]
