### PR TITLE
fix connection error appeared on zenith start

### LINKED ISSUE #507: zenith start prints a spurious error on successful start
```
$ ./target/debug/zenith start
Starting pageserver at 'localhost:64000' in .zenith
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9898/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (1)...
Pageserver started
```
That 'connect error' is confusing

### PR DESCRIPTION
**Pull request by LizardWizzard**
by introduction of a small delay before first connection try (50ms)

closes #507

### CODE REVIEW

File: control_plane/src/storage.rs [hunk 1]
```diff
@@ -120,6 +120,8 @@ impl PageServerNode {
         // It takes a while for the page server to start up. Wait until it is
         // open for business.
         for retries in 1..15 {
+            // add a short sleep before first try to avoid spurious error on the first check
```
Comment (funbringer) [inline control_plane/src/storage.rs:123]: > a short sleep before first try

The comment is puzzling: this sleep is called on every iteration. More importantly, does this really solve anything? If 1 sec is too much of a wait, could we just increase the frequency of polling?

Comment (LizardWizzard) [reply control_plane/src/storage.rs:123]: Hm, yeah, should move it up out of the loop. Increased polling period doesnt help, because this way there can be even more errors printed before successful startup

**Comment by lubennikovaav** [comment]
What if we just don't report this error for the first few retries?
```
if retires > 10
println!()
```

File: control_plane/src/storage.rs (hunk 1 above)
Comment (funbringer) [reply control_plane/src/storage.rs]: > because this way there can be even more errors printed before successful startup

Maybe we don't need those errors in the first place? We could replace them with a summary (e.g. "8 tries, success")

Comment (LizardWizzard) [reply control_plane/src/storage.rs]: IMO it is convenient to see them because sometimes I receive something like address already in use and can quickly stop the retries

**Comment by LizardWizzard** [comment]
> What if we just don't report this error for the first few retries?

See my reply to @funbringer comment

File: control_plane/src/storage.rs (hunk 1 above)
Comment (patins) [reply control_plane/src/storage.rs]: Can we modify pageserver to bind the sockets before daemonizing

Comment (LizardWizzard) [reply control_plane/src/storage.rs]: Nice idea, I thought that it would be messy to pass sync socket to asynchronous hyper server, but I found an API for that, so it feels smooth. Rearranged start_pageserver a bit

File: pageserver/src/bin/pageserver.rs [hunk 2]
```diff
@@ -337,9 +348,13 @@ fn start_pageserver(conf: &'static PageServerConf) -> Result<()> {
...
-    page_service_thread
-        .join()
-        .expect("Page service thread has panicked")?;
+    join_handles.push(page_service_thread);
 
+    // Initialize tenant manager.
+    tenant_mgr::init(conf);
+
+    for handle in join_handles.into_iter() {
+        handle.join().unwrap().unwrap()
```
Comment (funbringer) [inline pageserver/src/bin/pageserver.rs:357]: That's 2 many unwraps :) Could you replace each `unwrap` with `expect(...)` with a corresponding description?

**Comment by patins** [comment]
> ```
> if retires > 10
> println!()
> ```

I think you need to combine my suggestion with this one to achieve
* Noticeable failure when socket bind fails
* Not printing errors when we're just waiting for the server to come up

**Comment by LizardWizzard** [comment]
>Not printing errors when we're just waiting for the server to come up

I'm still missing the point of hiding several retries. If for example http thread dies from panic after the bind or panic originates from status handler itself, I would like to get the feedback faster so I can jump straight into the logs.

What do you think about printing the retry message but without an error in first few tries? It might be the middle ground for that :)

**Comment by kelvich** [comment]
IMO it makes sense to not to print any _expected_ errors. So during the start we can write 'Waiting pageserver to start ...' and add dot for each failed try until it reaches some limit and `failed to start in X seconds` error will be printed out. I think it quite an often pattern amount CLI tools. But dot should be printed only for expected error like failed connection and 500 http return code should be actually printed or thrown.

**Comment by kelvich** [comment]
And somewhat related: https://github.com/zenithdb/zenith/issues/525

**Comment by LizardWizzard** [comment]
This is how it looks like for completely unsuccessful case:
```
Starting pageserver at 'localhost:64000' in '.zenith'....
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (5)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (6)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (7)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (8)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (9)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (10)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (11)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (12)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (13)...
Pageserver not responding yet, err error sending request for url (http://127.0.0.1:9899/v1/status): error trying to connect: tcp connect error: Connection refused (os error 61) retrying (14)...
pageserver start failed: pageserver failed to start in 15 seconds
```
This is for one retry (how it was before socket bind was moved out of the listener thread)
```
Starting pageserver at 'localhost:64000' in '.zenith'. <--- one dot for one retry
Pageserver started
```
This is how it looks now after bind was moved
```
Starting pageserver at 'localhost:64000' in '.zenith'
Pageserver started
```

File: control_plane/src/storage.rs [hunk 3]
```diff
@@ -181,27 +192,22 @@ impl PageServerNode {
         builder
     }
 
-    pub fn check_status(&self) -> Result<()> {
-        let status = self
-            .http_request(Method::GET, format!("{}/{}", self.http_base_url, "status"))
+    pub fn check_status(&self) -> Result<(), reqwest::Error> {
```
Comment (patins) [inline control_plane/src/storage.rs:195]: I think we can use `reqwest::Result`

File: pageserver/src/bin/pageserver.rs [hunk 4]
```diff
@@ -337,9 +348,16 @@ fn start_pageserver(conf: &'static PageServerConf) -> Result<()> {
             page_service::thread_main(conf, auth, pageserver_listener, conf.auth_type)
         })?;
 
-    page_service_thread
-        .join()
-        .expect("Page service thread has panicked")?;
+    join_handles.push(page_service_thread);
 
+    // Initialize tenant manager.
+    tenant_mgr::init(conf);
```
Comment (patins) [inline pageserver/src/bin/pageserver.rs:354]: Why move this? Also, was it originally in the right place? Should the initialization happen before any of the worker threads that would touch `REPOSITORY`

**Review by patins — COMMENTED** [review]
Nice, can you add what the output looks like when one of the ports is already bound to?

File: pageserver/src/bin/pageserver.rs (hunk 4 above)
Comment (LizardWizzard) [reply pageserver/src/bin/pageserver.rs]: I think I was shuffling the code quite intensively and it ended up here. Agree with you, though it should work just fine because accesses to repo occur only during connection handling and by that time initialization completes. But yeah, it is better not to leave a place for errors there

**Comment by LizardWizzard** [comment]
@patins Start error with port already in use looks like that:
```
Starting pageserver at 'localhost:64000' in '.zenith'Error: Address already in use (os error 48)
pageserver start failed: Pageserver failed to start. See '.zenith/pageserver.log' for details.
```

**Review by patins — APPROVED** [review]
